spring.application.name=jewelryshop
server.port=8080

# --- EKLENEN KISIM: H2 Panelini Aktif Eder ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- SEN?N VER?TABANI AYARLARIN (Dosya tabanl?, kal?c?) ---
spring.datasource.url=jdbc:h2:file:./data/jewelrydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- SEN?N JPA AYARLARIN ---
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true